[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "I"]

[tool.pytest.ini_options]
addopts = "-q"
markers = [
    "array: involves arrays.",
    "backtrack: involves backtracking.",
    "dynamic: involves dynamic programming.",
    "graph: involves graphs.",
    "list: involves linked lists.",
    "math: involves mathematics.",
    "queue: involves queues.",
    "sorting: involves sorting arrays.",
    "stack: involves stacks.",
    "string: involves string manipulation.",
    "tree: involves trees with nodes.",
]
